---
- name: Create group "{{ group_name }}"
  group:
    name: "{{ group_name }}"
    state: present

- name: Create users and add to groups
  user:
    name: "{{ item.name }}"
    groups: ["{{ group_name }}", "wheel"]
  loop: "{{ user_accounts }}"

- name: Generate SSH keys for users
  ansible.builtin.user:
    name: "{{ item.name }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    ssh_key_bits: 2048
    ssh_key_comment: "{{ item.name }}@{{ inventory_hostname }}"
    ssh_key_passphrase: ""
  loop: "{{ user_accounts }}"

- name: Distribute SSH keys for users
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop: "{{ user_accounts }}"
