---
- name: Creating new xfs partition
  community.general.parted:
    device: "{{ disk_device }}"
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 4GiB

- name: Creating 2nd ext4 partitino
  community.general.parted:
    device: "{{ disk_device }}"
    number: 2
    flags: [ lvm ]
    state: present
    part_start: 4GiB
    part_end: 9GiB

- name:  formatting 1st partition
  filesystem:
    fstype: xfs
    dev: "{{ disk_device }}1"

- name: formatting 2nd partitions
  filesystem:
    fstype: ext4
    dev: "{{ disk_device }}2"

- name: mounting 1st partition
  mount:
    fstype: xfs
    src: "{{ disk_device }}1"
    path: /part1
    state: mounted

- name: mounting 2nd partition
  mount:
    fstype: ext4
    src: "{{ disk_device }}2"
    path: /part2
    state: mounted


  